CATEGORIES = {
    'GU' : 'Guitars',
    'GUAG' : 'Acoustic',
    'GUAGCC_1' : 'Acoustic - Classical Guitar Std',
    'GUAGCC_lh' : 'Acoustic - Classical Guitar LH',
    'GUBA' : 'Bass',
    'GUEG' : 'Electric',
    'GUAG_1' : 'Acoustic - 6 string',
    'GUAG_2' : 'Acoustic - 12 string',
    'GUAG_BG' : 'Acoustic - Beginners',
    'GUAG_lh' : 'Acousting - LH',
    'GUBA_1' : 'Bass - Solid Body',
    'GUBA_14' : 'Bass - 4 String SB',
    'GUBA_15' : 'Bass - 5 String SB',
    'GUBA_16' : 'Bass - 6 String SB',
    'GUBA_2' : 'Bass - Acoustic',
    'GUBA_3' : 'Bass - Fretless',
    'GUBA_BG' : 'Bass - Beginners',
    'GUBA_lh' : 'Bass - LH',
    'GUBASS' : 'Bass - Short Scale',
    'GUEG_1' : 'Electric - Solid Body',
    'GUEG_2' : 'Electric - Semi Acoustic',
    'GUEG_34' : 'Electric - 3/4 sized',
    'GUEG_7' : 'Electric - 7 String',
    'GUEG_8' : 'Electric - 8 String',
    'GUEG_BG' : 'Electric - Beginners',
    'GUEG_lh' : 'Electric - LH',
}